/**
 * Seed data ported from the original single-file app (reference/japan-itinerary.html).
 * Run `npx tsx scripts/seed.ts` to load it into Supabase.
 *
 * Image URLs are Wikimedia Commons thumbnails. Note: Wikimedia only serves a
 * fixed allowlist of thumbnail widths — 500px works, 640px does NOT (HTTP 400).
 * Keep the `500px-` prefix if you add more.
 */
import type { ActivityType } from '../lib/types';

const W = 'https://upload.wikimedia.org/wikipedia/commons/thumb';

const IMG = {
  sensoji: `${W}/4/43/Sensoji_2023.jpg/500px-Sensoji_2023.jpg`,
  sushi: `${W}/6/60/Sushi_platter.jpg/500px-Sushi_platter.jpg`,
  kappabashi: `${W}/e/e4/Kappabashi-dori_streetcorner_%28Kitchen_town_-_southern_end%29_Tokyo_Japan.jpg/500px-Kappabashi-dori_streetcorner_%28Kitchen_town_-_southern_end%29_Tokyo_Japan.jpg`,
  jcuisine: `${W}/5/57/Oseti.jpg/500px-Oseti.jpg`,
  tnm: `${W}/a/a5/Tokyo_National_Museum%2C_Honkan_2010.jpg/500px-Tokyo_National_Museum%2C_Honkan_2010.jpg`,
  ameyoko: `${W}/5/5e/Ueno_20241210_133139.jpg/500px-Ueno_20241210_133139.jpg`,
  akihabara: `${W}/6/60/Sotokanda%2C_Akihabara_Electric_Town_at_night_20231114.png/500px-Sotokanda%2C_Akihabara_Electric_Town_at_night_20231114.png`,
  meiji: `${W}/8/8b/Meiji_Jingu_2023-3.jpg/500px-Meiji_Jingu_2023-3.jpg`,
  takeshita: `${W}/b/bd/JRE-Harajuku-Station-07.jpg/500px-JRE-Harajuku-Station-07.jpg`,
  shibuyacross: `${W}/8/88/Shibuya_Crossing%2C_Aerial.jpg/500px-Shibuya_Crossing%2C_Aerial.jpg`,
  odaiba: `${W}/4/4a/Odaiba_close_up_-_2025_Jan_14_01-27PM.jpeg/500px-Odaiba_close_up_-_2025_Jan_14_01-27PM.jpeg`,
  fuji: `${W}/f/f8/View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg/500px-View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg`,
  kamo: `${W}/3/30/Kamogawa_sakura.jpg/500px-Kamogawa_sakura.jpg`,
  yakiniku: `${W}/b/b7/Yakiniku_002.jpg/500px-Yakiniku_002.jpg`,
  fushimi: `${W}/0/0e/Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg/500px-Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg`,
  kiyomizu: `${W}/3/3c/Kiyomizu.jpg/500px-Kiyomizu.jpg`,
  gion: `${W}/2/23/150124_Gion_Kyoto_Japan01s3.jpg/500px-150124_Gion_Kyoto_Japan01s3.jpg`,
  nishiki: `${W}/c/ce/Nishiki_Ichiba_by_matsuyuki.jpg/500px-Nishiki_Ichiba_by_matsuyuki.jpg`,
  ramen: `${W}/c/c3/Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg/500px-Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg`,
  osaka: `${W}/c/ca/Osaka_Castle_03bs3200.jpg/500px-Osaka_Castle_03bs3200.jpg`,
  dotonbori: `${W}/f/f4/Osaka_Dotonbori_Ebisu_Bridge.jpg/500px-Osaka_Dotonbori_Ebisu_Bridge.jpg`,
  izakaya: `${W}/b/b3/Izakaya_Exterior_Gotanda.jpg/500px-Izakaya_Exterior_Gotanda.jpg`,
  arashiyama: `${W}/c/c2/Arashiyama%2C_Part_II_-_Arashiyama7534.jpg/500px-Arashiyama%2C_Part_II_-_Arashiyama7534.jpg`,
  kinkakuji: `${W}/0/0f/Golden_Pavilion_Kinkaku-ji_water_mirror_2024.jpg/500px-Golden_Pavilion_Kinkaku-ji_water_mirror_2024.jpg`,
  abombdome: `${W}/7/77/Genbaku_Dome04-r.JPG/500px-Genbaku_Dome04-r.JPG`,
  peacepark: `${W}/b/b2/20181111_Hiroshima_Memorial_Cenotaph-1.jpg/500px-20181111_Hiroshima_Memorial_Cenotaph-1.jpg`,
  okonomiyaki: `${W}/5/59/Okonomiyaki_001.jpg/500px-Okonomiyaki_001.jpg`,
  itsukushima: `${W}/e/ef/Itsukushima_Shrine_Torii_Gate_%2813890465459%29.jpg/500px-Itsukushima_Shrine_Torii_Gate_%2813890465459%29.jpg`,
  kabukicho: `${W}/9/92/Kabukicho_red_gate_and_colorful_neon_street_signs_at_night%2C_Shinjuku%2C_Tokyo%2C_Japan.jpg/500px-Kabukicho_red_gate_and_colorful_neon_street_signs_at_night%2C_Shinjuku%2C_Tokyo%2C_Japan.jpg`,
  gyoen: `${W}/9/9d/Shinjuku_Gyoen_National_Garden_-_sakura_3.JPG/500px-Shinjuku_Gyoen_National_Garden_-_sakura_3.JPG`,
  camii: `${W}/2/25/Tokyo_Camii_2009.jpg/500px-Tokyo_Camii_2009.jpg`,
  chureito: `${W}/6/66/Chuurei-tou_Fujiyoshida_17025277650_c59733d6ba_o.jpg/500px-Chuurei-tou_Fujiyoshida_17025277650_c59733d6ba_o.jpg`,
  ginza: `${W}/5/5b/Ginza-WAKO_at_night.jpg/500px-Ginza-WAKO_at_night.jpg`,
  hakone: `${W}/b/b5/View_of_Mount_Fuji_from_Lake_Ashi.jpg/500px-View_of_Mount_Fuji_from_Lake_Ashi.jpg`,
  hoto: `${W}/a/a0/Houtou.jpg/500px-Houtou.jpg`,
  kebab: `${W}/5/5b/Lula_kebab_2.jpg/500px-Lula_kebab_2.jpg`,
  daibutsu: `${W}/c/cf/230128_Kamakura_Daibutsu_Japan04s3.jpg/500px-230128_Kamakura_Daibutsu_Japan04s3.jpg`,
  kawaguchiko: `${W}/1/18/KawaguchiKo.jpg/500px-KawaguchiKo.jpg`,
  motosu: `${W}/5/54/Lake_Motosu03.jpg/500px-Lake_Motosu03.jpg`,
  nakano: `${W}/3/35/Nakano_broadway_entrance.JPG/500px-Nakano_broadway_entrance.JPG`,
  narusawa: `${W}/5/58/Narusawa_Hyoketsu_Entrance_20161025.jpg/500px-Narusawa_Hyoketsu_Entrance_20161025.jpg`,
  nikko: `${W}/2/26/200801_Nikko_Tosho-gu_Nikko_Japan03s3.jpg/500px-200801_Nikko_Tosho-gu_Nikko_Japan03s3.jpg`,
  shibuya: `${W}/3/3a/Shibuya_skyline_from_Tokyu_Plaza_in_Omotesando%2C_Harajuku%2C_Tokyo%2C_2024_May.jpg/500px-Shibuya_skyline_from_Tokyu_Plaza_in_Omotesando%2C_Harajuku%2C_Tokyo%2C_2024_May.jpg`,
  shinjuku: `${W}/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/500px-Skyscrapers_of_Shinjuku_2009_January.jpg`,
  tsukiji: `${W}/2/21/Tsukiji_2015.jpg/500px-Tsukiji_2015.jpg`,
  wagyu: `${W}/c/c1/Tajimagyu2.jpg/500px-Tajimagyu2.jpg`,
  saiko: `${W}/c/c6/Saiko_-_Saiko6828.jpg/500px-Saiko_-_Saiko6828.jpg`,
  omoide: `${W}/a/a4/Omoide-Yokocho-Shinjuku-01.jpg/500px-Omoide-Yokocho-Shinjuku-01.jpg`,
  oshino: `${W}/2/22/231028_Waku-ike_Oshino_Hakkai_springs_Oshino_Yamanashi_pref_Japan01s3.jpg/500px-231028_Waku-ike_Oshino_Hakkai_springs_Oshino_Yamanashi_pref_Japan01s3.jpg`,
  sumo: `${W}/c/c2/Ryogoku_Great_Sumo_Hall.jpg/500px-Ryogoku_Great_Sumo_Hall.jpg`,
  teamlab: `${W}/c/c3/TeamLab_Borderless%2C_Odaiba%2C_Tokyo%2C_Japan_%2849070633351%29.jpg/500px-TeamLab_Borderless%2C_Odaiba%2C_Tokyo%2C_Japan_%2849070633351%29.jpg`,
  nezu: `${W}/d/da/Nezu_Shrine_2010.jpg/500px-Nezu_Shrine_2010.jpg`,
  yanaka: `${W}/5/51/Tokyo_-_Yanaka_143.jpg/500px-Tokyo_-_Yanaka_143.jpg`,
  rikugien: `${W}/2/2b/Rikugien-10-2009-fujishirotoge02.jpg/500px-Rikugien-10-2009-fujishirotoge02.jpg`,
  shimokita: `${W}/5/59/Shimokitazawa_Street_2015.jpg/500px-Shimokitazawa_Street_2015.jpg`,
} as const;

/** Google Maps search link helper (was `M` in the original file). */
const M = (q: string) => `https://www.google.com/maps/search/?api=1&query=${q}`;

export interface SeedActivity {
  time: string | null;
  title: string;
  type: ActivityType;
  area: string | null;
  note: string | null;
  map_url: string | null;
  image_url: string | null;
  halal?: boolean;
  book?: boolean;
  opt?: boolean;
}

export interface SeedDay {
  date: string;
  dow: string | null;
  title: string | null;
  note: string | null;
  activities: SeedActivity[];
}

export interface SeedSegment {
  id: string;
  code: string;
  phase: string;
  name: string;
  jp: string;
  date_start: string;
  date_end: string;
  nights: number;
  travelers: number;
  color: string;
  stay: string;
  stay_note: string;
  climate: string;
  mosque: string;
  transit_icon: string;
  transit_html: string;
  /** Home / endpoint marker — route ribbon only, no day-by-day section. */
  is_terminus?: boolean;
  days: SeedDay[];
}

export const SEED: SeedSegment[] = [
  /* ---------------- TOKYO I ---------------- */
  {
    id: 'tokyo1',
    code: 'TYO',
    phase: 'Part 1 · arrival',
    name: 'Tokyo',
    jp: '東京',
    date_start: 'Oct 29',
    date_end: 'Nov 4',
    nights: 6,
    travelers: 7,
    color: 'var(--tokyo)',
    stay: 'Kaneda Apartment · 1-chōme-4-7 Misuji, Taito City, Tokyo 111-0055',
    stay_note: '5–10 min walk to Asakusa; Akihabara & Ueno one stop away',
    climate: 'Mild — 12–18°C days, cool evenings. Low rain.',
    mosque: 'Okachimachi Mosque (Ueno) · prayer rooms at Ueno & Tokyo stns',
    transit_icon: '✈',
    transit_html:
      '<b>Arrive night of Oct 29.</b> Narita → Keisei Skyliner to Ueno (41 min) + Ginza line to Asakusa; or Haneda → Asakusa line direct (~50 min). Keep the first night light.',
    days: [
      {
        date: 'Oct 29',
        dow: 'Wed',
        title: 'Land & settle',
        note: 'Tired-group mode: drop bags, eat close, sleep.',
        activities: [
          {
            time: 'Night',
            title: 'Check in at Misuji apartment',
            type: 'transit',
            area: 'Asakusa',
            note: "Sort keys, luggage, tomorrow's plan.",
            map_url: M('1-4-7+Misuji+Taito+Tokyo'),
            image_url: null,
          },
          {
            time: 'Dinner',
            title: 'Honolu Premier Asakusa (halal ramen)',
            type: 'food',
            area: 'Asakusa',
            halal: true,
            note: 'Creamy chicken paitan — no pork, no alcohol in the cooking. ~1 min from Senso-ji, prayer room on the 2nd floor. Forgiving for 7 late arrivals. (Naritaya, the old pick here, closed permanently.)',
            map_url: M('Honolu+Premier+Asakusa'),
            image_url: IMG.ramen,
          },
        ],
      },
      {
        date: 'Oct 30',
        dow: 'Thu',
        title: 'Asakusa · Kappabashi · Ryogoku',
        note: 'Barely leaves the neighbourhood. Kappabashi is a cooking-nerd highlight.',
        activities: [
          {
            time: '9:00',
            title: 'Sensō-ji, Kaminarimon & Nakamise',
            type: 'sight',
            area: 'Asakusa',
            note: "Go early before Nakamise fills. Note: most street stalls aren't halal — save real meals for verified spots.",
            map_url: M('Senso-ji+Temple'),
            image_url: IMG.sensoji,
          },
          {
            time: '12:30',
            title: 'Sushiken Asakusa (halal sushi)',
            type: 'food',
            area: 'Asakusa',
            halal: true,
            note: "Halal-certified since 2002, counter seating — split into 2 groups of 3–4. Alt: LUXE Burgers & Sunny's Table.",
            map_url: M('Asakusa+Sushi+Ken'),
            image_url: IMG.sushi,
          },
          {
            time: '14:00',
            title: 'Kappabashi Kitchen Town',
            type: 'shop',
            area: 'Kappabashi',
            note: 'Pro knives, ceramics, plastic-food shops. 10 min from Asakusa — better than a Skytree queue.',
            map_url: M('Kappabashi+Kitchen+Town'),
            image_url: IMG.kappabashi,
          },
          {
            time: '16:00',
            title: 'Ryōgoku — sumo & Edo history',
            type: 'culture',
            area: 'Ryogoku',
            note: 'Sumo Museum / Edo-Tokyo area. Check for a tournament or morning practice window. Easy to split the group here.',
            map_url: M('Ryogoku+Sumo'),
            image_url: IMG.sumo,
          },
          {
            time: '19:00',
            title: 'Sankyu Halal Japanese Food',
            type: 'food',
            area: 'Asakusa',
            halal: true,
            note: 'Broad Japanese halal menu — good for sharing across 7.',
            map_url: M('Sankyu+Halal+Asakusa'),
            image_url: IMG.jcuisine,
          },
        ],
      },
      {
        date: 'Oct 31',
        dow: 'Fri',
        title: 'Ueno · Akihabara',
        note: null,
        activities: [
          {
            time: '9:30',
            title: 'Ueno Park & Tokyo National Museum',
            type: 'sight',
            area: 'Ueno',
            note: 'Swap museum for Ueno Zoo if the group prefers. Ameyoko market alongside for snacks.',
            map_url: M('Ueno+Park'),
            image_url: IMG.tnm,
          },
          {
            time: '12:30',
            title: 'Ameyoko Market browse + lunch',
            type: 'shop',
            area: 'Ueno',
            note: 'Street food & bargain stalls under the tracks.',
            map_url: M('Ameyoko'),
            image_url: IMG.ameyoko,
          },
          {
            time: '14:00',
            title: 'Akihabara — electronics & arcades',
            type: 'shop',
            area: 'Akihabara',
            note: 'Anime/gaming stores, retro games, arcades (GiGO, Super Potato). Let people split & regroup.',
            map_url: M('Akihabara+Electric+Town'),
            image_url: IMG.akihabara,
          },
          {
            time: '19:00',
            title: 'Halal dinner near Okachimachi',
            type: 'food',
            area: 'Ueno',
            halal: true,
            note: 'Real cluster of halal spots by the Okachimachi mosque.',
            map_url: M('halal+restaurant+Okachimachi'),
            image_url: IMG.kebab,
          },
        ],
      },
      {
        date: 'Nov 1',
        dow: 'Sat',
        title: 'Shibuya · Harajuku · Shinjuku',
        note: 'West-side classics. Expect Saturday crowds.',
        activities: [
          {
            time: '9:00',
            title: 'Meiji Shrine',
            type: 'sight',
            area: 'Harajuku',
            note: 'Calm forest shrine — best before the Harajuku rush.',
            map_url: M('Meiji+Shrine'),
            image_url: IMG.meiji,
          },
          {
            time: '11:00',
            title: 'Takeshita Street, Harajuku',
            type: 'shop',
            area: 'Harajuku',
            note: 'Youth fashion, crepes, chaos.',
            map_url: M('Takeshita+Street'),
            image_url: IMG.takeshita,
          },
          {
            time: '13:00',
            title: 'Shibuya Crossing + Shibuya Sky',
            type: 'sight',
            area: 'Shibuya',
            book: true,
            note: 'Book Shibuya Sky timed slot ahead for a group photo from above.',
            map_url: M('Shibuya+Sky'),
            image_url: IMG.shibuyacross,
          },
          {
            time: '18:00',
            title: 'Omoide Yokocho + Shinjuku Tei dinner',
            type: 'food',
            area: 'Shinjuku',
            halal: true,
            note: 'Wander the alley for atmosphere (much is pork/alcohol) then eat at Halal Wagyu Ramen Shinjuku Tei.',
            map_url: M('Halal+Wagyu+Ramen+Shinjuku+Tei'),
            image_url: IMG.omoide,
          },
        ],
      },
      {
        date: 'Nov 2',
        dow: 'Sun',
        title: 'Tsukiji · Ginza · Odaiba',
        note: null,
        activities: [
          {
            time: '8:30',
            title: 'Tsukiji Outer Market breakfast',
            type: 'food',
            area: 'Tsukiji',
            note: 'Seafood stalls & knives — check individual vendors for halal before eating.',
            map_url: M('Tsukiji+Outer+Market'),
            image_url: IMG.tsukiji,
          },
          {
            time: '11:00',
            title: 'Ginza stroll',
            type: 'shop',
            area: 'Ginza',
            note: 'Flagship stores, Itoya stationery, Uniqlo/Muji flagships.',
            map_url: M('Ginza'),
            image_url: IMG.ginza,
          },
          {
            time: '14:00',
            title: 'teamLab Planets, Odaiba',
            type: 'culture',
            area: 'Odaiba',
            book: true,
            note: 'BOOK NOW for 7 — timed group tickets sell out. Barefoot digital-art experience.',
            map_url: M('teamLab+Planets+TOKYO'),
            image_url: IMG.teamlab,
          },
          {
            time: '17:30',
            title: 'Gundam statue + Rainbow Bridge',
            type: 'sight',
            area: 'Odaiba',
            note: 'DiverCity life-size Gundam; bayside views at dusk.',
            map_url: M('DiverCity+Tokyo+Plaza+Gundam'),
            image_url: IMG.odaiba,
          },
        ],
      },
      {
        date: 'Nov 3',
        dow: 'Mon',
        title: 'Free day — gaming crawl or Kamakura',
        note: 'Low-planning day before the travel day. Pick one.',
        activities: [
          {
            time: 'Option A',
            title: 'Ikebukuro + Nakano Broadway gaming crawl',
            type: 'free',
            area: 'Ikebukuro / Nakano',
            note: 'Pokémon Center Mega Tokyo, Round1/GiGO arcades, then Nakano Broadway for retro games & collectibles. Zero tickets, easy to split.',
            map_url: M('Nakano+Broadway'),
            image_url: IMG.nakano,
          },
          {
            time: 'Option B',
            title: 'Kamakura day trip',
            type: 'nature',
            area: 'Kamakura',
            opt: true,
            note: 'Great Buddha, temples, coast — ~1 hr each way. Better if the group wants scenery before Fuji.',
            map_url: M('Kamakura'),
            image_url: IMG.daibutsu,
          },
        ],
      },
      {
        date: 'Nov 4',
        dow: 'Tue',
        title: 'Transfer to Kawaguchiko',
        note: null,
        activities: [
          {
            time: 'AM',
            title: 'Pack, last Asakusa coffee, check out',
            type: 'transit',
            area: 'Asakusa',
            note: 'Consider forwarding a bag ahead if not needed at the lake.',
            map_url: null,
            image_url: null,
          },
        ],
      },
    ],
  },

  /* ---------------- KAWAGUCHIKO ---------------- */
  {
    id: 'kawa',
    code: 'KWG',
    phase: 'Part 2 · Mt Fuji',
    name: 'Kawaguchiko',
    jp: '河口湖',
    date_start: 'Nov 4',
    date_end: 'Nov 7',
    nights: 3,
    travelers: 7,
    color: 'var(--fuji)',
    stay: '新倉2921-1, Fujiyoshida, Yamanashi 403-0011',
    stay_note:
      'Arakura, Fujiyoshida — walking distance to Chureito Pagoda. Not on the lake: Kawaguchiko Stn is ~10 min by car (or Shimoyoshida Stn + one stop on the Fujikyu line), so the rental car matters.',
    climate: 'Cold mornings 2–6°C, days ~13–17°C. Dress warm for sunrise.',
    mosque: "Fujikawaguchiko Masjid · Jumu'ah ~12:45, halal café attached",
    transit_icon: '🚌',
    transit_html:
      '<b>Tokyo → Kawaguchiko.</b> Highway bus Shinjuku → Kawaguchiko Stn (~1h45–2h), or JR Chūō → Ōtsuki → Fujikyū line. <b>Pick up the rental car</b> near arrival — it changes everything below (no 6pm last-bus problem).',
    days: [
      {
        date: 'Nov 4',
        dow: 'Tue',
        title: 'Arrive · Maple Corridor by night',
        note: 'Momiji Festival runs all Nov; early = golden-to-red + illuminations.',
        activities: [
          {
            time: 'PM',
            title: 'Check in, orient by the lake',
            type: 'transit',
            area: 'Funatsu',
            note: 'Grab the car keys, settle in.',
            map_url: null,
            image_url: null,
          },
          {
            time: '17:00',
            title: 'Lake Kawaguchi Maple Corridor (lit)',
            type: 'nature',
            area: 'North shore',
            note: 'Illuminated from ~4:30pm to 9:30–10pm. With the car you can stay late — no last-bus rush.',
            map_url: M('Lake+Kawaguchi+Maple+Corridor'),
            image_url: IMG.kawaguchiko,
          },
          {
            time: '19:30',
            title: 'IDATEN BETTEI Honten',
            type: 'food',
            area: 'Funatsu',
            halal: true,
            note: 'Halal-certified wagyu sushi / tempura / ramen courses, prayer room on site. Drive over from Arakura (~10 min). Reserve for 7.',
            map_url: M('IDATEN+BETTEI+Honten'),
            image_url: IMG.wagyu,
          },
        ],
      },
      {
        date: 'Nov 5',
        dow: 'Wed',
        title: 'Fuji viewpoints loop',
        note: 'Clear Fuji is likeliest 6–9am before cloud builds.',
        activities: [
          {
            time: '6:30',
            title: 'Sunrise Fuji from the lakeshore',
            type: 'nature',
            area: 'North shore',
            opt: true,
            note: 'If skies are clear, step out early. With the car you can relocate to Oishi Park for a cleaner angle.',
            map_url: M('Oishi+Park+Kawaguchiko'),
            image_url: IMG.fuji,
          },
          {
            time: '9:00',
            title: 'Chureito Pagoda',
            type: 'sight',
            area: 'Fujiyoshida',
            note: 'The classic pagoda + Fuji shot, and you are staying in Arakura — walk it and skip the ~¥1,000–1,500 parking. Arrive early to beat tour groups; ~400 steps up.',
            map_url: M('Chureito+Pagoda'),
            image_url: IMG.chureito,
          },
          {
            time: '12:00',
            title: 'Oshino Hakkai + lunch',
            type: 'nature',
            area: 'Oshino',
            note: 'Crystal spring-fed ponds village. Food stalls (mochi, grilled corn).',
            map_url: M('Oshino+Hakkai'),
            image_url: IMG.oshino,
          },
          {
            time: '15:00',
            title: 'Mt Fuji Panoramic Ropeway + Oishi Park',
            type: 'sight',
            area: 'North shore',
            note: 'Late afternoon = shorter queues, golden hour. Oishi Park for the postcard Fuji-over-lake view.',
            map_url: M('Mt+Fuji+Panoramic+Ropeway'),
            image_url: IMG.kawaguchiko,
          },
          {
            time: '19:00',
            title: 'Aladdin Indo Restaurant & Kebab House',
            type: 'food',
            area: 'Funatsu',
            halal: true,
            note: 'Halal, lakeside outdoor seating. Well-priced kebabs & curry.',
            map_url: M('Aladdin+Indo+Restaurant+Kebab+Kawaguchiko'),
            image_url: IMG.kebab,
          },
        ],
      },
      {
        date: 'Nov 6',
        dow: 'Thu',
        title: 'Fuji Five Lakes drive',
        note: 'The day the car earns its keep.',
        activities: [
          {
            time: '9:30',
            title: 'Saiko Iyashi-no-Sato Nenba',
            type: 'culture',
            area: 'Lake Saiko',
            note: 'Rebuilt Edo thatched-roof village; pottery workshops, Fuji backdrop.',
            map_url: M('Saiko+Iyashi+no+Sato+Nenba'),
            image_url: IMG.saiko,
          },
          {
            time: '12:45',
            title: "Jumu'ah at Fujikawaguchiko Masjid",
            type: 'culture',
            area: 'Funatsu',
            halal: true,
            opt: true,
            note: 'Friday prayer ~12:45; halal café next door for lunch. Skip if not needed.',
            map_url: M('Fujikawaguchiko+Masjid'),
            image_url: null,
          },
          {
            time: '14:30',
            title: 'Narusawa Ice Cave / Fugaku Wind Cave',
            type: 'nature',
            area: 'Aokigahara edge',
            note: 'Lava caves in the forest — short, cold, fun.',
            map_url: M('Narusawa+Ice+Cave'),
            image_url: IMG.narusawa,
          },
          {
            time: '16:00',
            title: 'Lake Motosu (¥1000-note view)',
            type: 'nature',
            area: 'West lakes',
            note: 'The Fuji view on the old ¥1,000 note. Golden-hour drive back.',
            map_url: M('Lake+Motosu'),
            image_url: IMG.motosu,
          },
          {
            time: '19:00',
            title: 'HOUTO LABO — halal hōtō',
            type: 'food',
            area: 'Kawaguchiko',
            halal: true,
            note: 'Local hearty miso hotpot noodles, halal. Good one to try.',
            map_url: M('HOTO+LABO+Kawaguchiko'),
            image_url: IMG.hoto,
          },
        ],
      },
      {
        date: 'Nov 7',
        dow: 'Fri',
        title: 'Return car · onward to Kyoto',
        note: null,
        activities: [
          {
            time: 'AM',
            title: 'Last Fuji check, pack, return rental',
            type: 'transit',
            area: 'Kawaguchiko',
            note: 'Fuel up & return the car near the station.',
            map_url: null,
            image_url: null,
          },
        ],
      },
    ],
  },

  /* ---------------- KYOTO ---------------- */
  {
    id: 'kyoto',
    code: 'KIX',
    phase: 'Part 3 · Kansai · group of 5',
    name: 'Kyoto',
    jp: '京都',
    date_start: 'Nov 7',
    date_end: 'Nov 11',
    nights: 4,
    travelers: 5,
    color: 'var(--kyoto)',
    stay: '京都府京都市下京区西木屋町通五条下る南京極町48番地3 (600-8117)',
    stay_note: 'Central — walk to Gion, Nishiki & Kyoto Stn area; riverside',
    climate: 'Like Tokyo — 11–18°C, peak autumn colour building through Nov.',
    mosque: 'Kyoto Camii (near Kyoto Stn) · Al Rashid Mosque on Kiyamachi (near you)',
    transit_icon: '🚄',
    transit_html:
      '<b>Kawaguchiko → Kyoto (2 people peel off, now 5).</b> Bus/train to Mishima Stn (~1.5h), then Shinkansen Mishima → Kyoto (~2h15). Budget a half-day. Forwarding luggage ahead makes it painless.',
    days: [
      {
        date: 'Nov 7',
        dow: 'Fri',
        title: 'Arrive · Kamo River & Gion evening',
        note: null,
        activities: [
          {
            time: 'PM',
            title: 'Check in, walk Kiyamachi & the Kamo River',
            type: 'transit',
            area: 'Shimogyo',
            note: 'Your street is lined with canals & lantern-lit bars — stroll north into Gion.',
            map_url: M('Kiyamachi+dori+Kyoto'),
            image_url: IMG.kamo,
          },
          {
            time: '19:00',
            title: 'GYUMON — halal wagyu yakiniku & ramen',
            type: 'food',
            area: 'Gion-Higashiyama',
            halal: true,
            note: 'Grill premium wagyu tableside; social for a group of 5. Alt: Shinjukutei Gion (halal wagyu ramen).',
            map_url: M('GYUMON+Gion+halal+wagyu'),
            image_url: IMG.yakiniku,
          },
        ],
      },
      {
        date: 'Nov 8',
        dow: 'Sat',
        title: 'Higashiyama — the temple run',
        note: 'Front-load Fushimi Inari before the crowds.',
        activities: [
          {
            time: '7:00',
            title: 'Fushimi Inari Taisha (early)',
            type: 'sight',
            area: 'Fushimi',
            note: "Thousands of vermilion torii. Before 7:30 it's nearly empty; take the right-hand path up.",
            map_url: M('Fushimi+Inari+Taisha'),
            image_url: IMG.fushimi,
          },
          {
            time: '10:30',
            title: 'Kiyomizu-dera + Ninenzaka/Sannenzaka',
            type: 'sight',
            area: 'Higashiyama',
            note: 'Hilltop temple & preserved lanes of shops and tea houses.',
            map_url: M('Kiyomizu-dera'),
            image_url: IMG.kiyomizu,
          },
          {
            time: '14:00',
            title: 'Gion & Hanamikoji',
            type: 'culture',
            area: 'Gion',
            note: 'Machiya streets, geisha district. Be respectful on the private lanes.',
            map_url: M('Gion+Hanamikoji'),
            image_url: IMG.gion,
          },
          {
            time: '16:00',
            title: 'Nishiki Market',
            type: 'food',
            area: 'Nakagyo',
            note: '"Kyoto\'s kitchen" — sample stalls (confirm halal per item). Bring cash.',
            map_url: M('Nishiki+Market'),
            image_url: IMG.nishiki,
          },
          {
            time: '19:00',
            title: 'Halal yakiniku / ramen dinner',
            type: 'food',
            area: 'Central',
            halal: true,
            note: 'Yakiniku Ichimaru (Gion) or back to a halal ramen spot.',
            map_url: M('Yakiniku+Ichimaru+Gion+halal'),
            image_url: IMG.ramen,
          },
        ],
      },
      {
        date: 'Nov 9',
        dow: 'Sun',
        title: 'Osaka day trip',
        note: '~15 min by Shinkansen or ~40 min rapid train from Kyoto.',
        activities: [
          {
            time: '9:30',
            title: 'Osaka Castle & park',
            type: 'sight',
            area: 'Chuo, Osaka',
            note: 'Interior is a modern museum; grounds & views are the draw.',
            map_url: M('Osaka+Castle'),
            image_url: IMG.osaka,
          },
          {
            time: '13:00',
            title: 'Dōtonbori & Namba',
            type: 'sight',
            area: 'Namba, Osaka',
            note: 'Glico sign, canal, street-food theatre. Shinsekai/Tsutenkaku nearby if time.',
            map_url: M('Dotonbori'),
            image_url: IMG.dotonbori,
          },
          {
            time: '18:00',
            title: 'Tsuki no Odori — halal izakaya',
            type: 'food',
            area: 'Nishi, Osaka',
            halal: true,
            note: "One of Japan's few halal-certified izakayas — yakitori, karaage, hot pot.",
            map_url: M('Tsuki+no+Odori+halal+Osaka'),
            image_url: IMG.izakaya,
          },
        ],
      },
      {
        date: 'Nov 10',
        dow: 'Mon',
        title: 'Arashiyama + NW Kyoto',
        note: "Swap this whole day for the Hiroshima trip below if you'd rather do Hiroshima now (recommended).",
        activities: [
          {
            time: '8:00',
            title: 'Arashiyama Bamboo Grove (early)',
            type: 'nature',
            area: 'Arashiyama',
            note: "Go before 8:30 or it's wall-to-wall. Tenryū-ji garden alongside.",
            map_url: M('Arashiyama+Bamboo+Grove'),
            image_url: IMG.arashiyama,
          },
          {
            time: '11:00',
            title: 'Kinkaku-ji (Golden Pavilion)',
            type: 'sight',
            area: 'Kita',
            note: 'Gold-leaf temple over a reflecting pond — stunning with autumn colour.',
            map_url: M('Kinkaku-ji'),
            image_url: IMG.kinkakuji,
          },
          {
            time: '14:00',
            title: 'Optional: Hiroshima round-trip instead',
            type: 'transit',
            area: '—',
            opt: true,
            note: 'RECOMMENDED SWAP: do Hiroshima today as a round trip from Kyoto (leave luggage here), then Nov 11 is a clean, relaxed Kyoto → Tokyo day. See the Hiroshima stop for details.',
            map_url: null,
            image_url: null,
          },
        ],
      },
      {
        date: 'Nov 11',
        dow: 'Tue',
        title: 'Depart Kyoto',
        note: 'See the Hiroshima stop for the two routing options.',
        activities: [
          {
            time: 'AM',
            title: 'Check out · forward luggage to Shinjuku',
            type: 'transit',
            area: 'Kyoto Stn',
            note: 'Takkyūbin your bags ahead to the Tokyo Part 2 stay so the Hiroshima detour is hands-free.',
            map_url: null,
            image_url: null,
          },
        ],
      },
    ],
  },

  /* ---------------- HIROSHIMA ---------------- */
  {
    id: 'hiro',
    code: 'HIJ',
    phase: 'Nov 11 · day trip — decide the routing',
    name: 'Hiroshima',
    jp: '広島',
    date_start: 'Nov 11',
    date_end: 'Nov 11',
    nights: 0,
    travelers: 5,
    color: 'var(--hiro)',
    stay: 'No overnight — day trip only',
    stay_note: 'Coin lockers at Hiroshima Stn for day bags',
    climate: 'Coastal & mild, ~13–18°C.',
    mosque: 'Hiroshima Muslim community near the university; limited halal downtown',
    transit_icon: '⚠',
    transit_html:
      '<b>The honest read:</b> Kyoto → Hiroshima is ~1h40; Hiroshima → Tokyo is ~4h. Doing both on Nov 11 = ~6h of Shinkansen backtracking past Kyoto, with luggage, around a heavy museum — a ~14h day, and Miyajima won\'t fit. <b>Cleaner:</b> do this as a round-trip from Kyoto on Nov 10 (Miyajima fits), then a normal Kyoto → Tokyo run on the 11th. Both options are below — keep one, delete the other.',
    days: [
      {
        date: 'Option 1',
        dow: 'On the 11th',
        title: 'Hiroshima → straight to Tokyo (long day)',
        note: "Peace Park only; heavy but doable if you're set on this shape.",
        activities: [
          {
            time: '~7:00',
            title: 'Early Nozomi: Kyoto → Hiroshima',
            type: 'transit',
            area: 'Shinkansen',
            note: '~1h40. Stash day bags in Hiroshima Stn lockers (main luggage already forwarded).',
            map_url: null,
            image_url: null,
          },
          {
            time: '9:30',
            title: 'Peace Memorial Park & Museum',
            type: 'culture',
            area: 'Naka, Hiroshima',
            note: "A-Bomb Dome, Cenotaph, Museum. Give it 2.5–3h — it deserves the time and it's sobering.",
            map_url: M('Hiroshima+Peace+Memorial+Park'),
            image_url: IMG.peacepark,
          },
          {
            time: '13:30',
            title: 'Okonomiyaki lunch (Hiroshima-style)',
            type: 'food',
            area: 'Downtown',
            note: 'Confirm halal/ingredients individually — options are limited downtown.',
            map_url: M('Hiroshima+okonomiyaki'),
            image_url: IMG.okonomiyaki,
          },
          {
            time: '15:00',
            title: 'Nozomi: Hiroshima → Tokyo',
            type: 'transit',
            area: 'Shinkansen',
            note: '~4h. Arrive Shinjuku ~8–9pm. Bags already at the hotel.',
            map_url: null,
            image_url: null,
          },
        ],
      },
      {
        date: 'Option 1b',
        dow: 'Same day, fly instead',
        title: 'Hiroshima → Tokyo by air (comparison)',
        note: 'Checked: door-to-door this is a wash vs the train — Hiroshima Airport is ~50 min outside the city, which eats the flight-time saving. Worth it mainly if fares are genuinely cheap for the group.',
        activities: [
          {
            time: '13:45',
            title: 'Streetcar/taxi to city, then limousine bus to HIJ',
            type: 'transit',
            area: 'Hiroshima',
            note: '~50 min bus to the airport, add buffer for traffic. Bus stop is outside Arrivals, 1st floor.',
            map_url: null,
            image_url: null,
          },
          {
            time: '~15:30',
            title: 'Check-in + security, HIJ',
            type: 'transit',
            area: 'Hiroshima Airport',
            note: 'Domestic — arrive ~40 min before boarding. JAL/ANA run ~14–15 flights/day to Haneda.',
            map_url: null,
            image_url: null,
          },
          {
            time: '~16:30',
            title: 'Flight HIJ → HND',
            type: 'transit',
            area: 'In flight',
            note: '1h15–1h40 in the air. ~¥ varies a lot, sometimes cheaper than Shinkansen if booked early; sometimes not.',
            map_url: null,
            image_url: null,
          },
          {
            time: '~18:00',
            title: 'Haneda → Shinjuku',
            type: 'transit',
            area: 'Tokyo',
            note: 'Keikyu + JR, or airport limousine bus — ~40–45 min. Compare to Tokyo Stn → Shinjuku (~15 min) on the train option.',
            map_url: null,
            image_url: null,
          },
        ],
      },
      {
        date: 'Option 2',
        dow: 'Best — on Nov 10',
        title: 'Hiroshima round-trip from Kyoto (recommended)',
        note: 'Delete this OR Option 1. If you keep this, Nov 11 becomes a simple Kyoto → Tokyo day.',
        activities: [
          {
            time: '6:45',
            title: 'Nozomi: Kyoto → Hiroshima',
            type: 'transit',
            area: 'Shinkansen',
            note: "~1h40. No luggage — you're coming back to Kyoto tonight.",
            map_url: null,
            image_url: null,
          },
          {
            time: '9:00',
            title: 'Peace Memorial Park & Museum',
            type: 'culture',
            area: 'Naka, Hiroshima',
            note: 'Full unhurried visit.',
            map_url: M('Hiroshima+Peace+Memorial+Park'),
            image_url: IMG.abombdome,
          },
          {
            time: '12:30',
            title: 'Ferry to Miyajima · Itsukushima Shrine',
            type: 'sight',
            area: 'Miyajima',
            note: 'Floating torii gate, wild deer, island walks. The reason to do this version.',
            map_url: M('Itsukushima+Shrine+Miyajima'),
            image_url: IMG.itsukushima,
          },
          {
            time: '17:30',
            title: 'Nozomi back to Kyoto',
            type: 'transit',
            area: 'Shinkansen',
            note: 'Sleep in your own Kyoto bed; travel clean to Tokyo tomorrow.',
            map_url: null,
            image_url: null,
          },
        ],
      },
    ],
  },

  /* ---------------- TOKYO II ---------------- */
  {
    id: 'tokyo2',
    code: 'SJK',
    phase: 'Part 4 · group of 5',
    name: 'Tokyo — Shinjuku',
    jp: '新宿',
    date_start: 'Nov 11',
    date_end: 'Nov 16',
    nights: 5,
    travelers: 5,
    color: 'var(--tokyo2)',
    stay: 'Shinjuku, near the 24/7 Don Quijote (Kabukichō)',
    stay_note: "Nightlife & transit hub; Shinjuku Stn is Tokyo's spine",
    climate: 'Mild, 11–17°C. Autumn colour peaks mid–late Nov in the parks.',
    mosque: "Tokyo Camii (Yoyogi-Uehara) — grand mosque + halal market; Jumu'ah",
    transit_icon: '🏙',
    transit_html:
      '<b>Arrive Shinjuku Nov 11</b> (from Hiroshima ~8–9pm, or a relaxed Kyoto run if you took Option 2). Bags should already be here via takkyūbin.',
    days: [
      {
        date: 'Nov 11',
        dow: 'Tue',
        title: 'Land in Shinjuku',
        note: 'Keep it easy after the travel day.',
        activities: [
          {
            time: 'Night',
            title: 'Check in + Kabukichō neon walk',
            type: 'sight',
            area: 'Shinjuku',
            note: 'Godzilla head, Golden Gai alleys from the outside, the big 3D cat screen. Atmosphere is heavy on pork/alcohol — this is a walk, not a meal.',
            map_url: M('Kabukicho+Shinjuku'),
            image_url: IMG.kabukicho,
          },
          {
            time: 'Late',
            title: 'Nasco Halal Food, Hyakuninchō',
            type: 'food',
            area: 'Shin-Ōkubo',
            halal: true,
            note: 'Halal-certified Pakistani/Bangladeshi — mutton biryani, kebabs. Open to ~22:00, so it survives a late arrival. One stop from Shinjuku.',
            map_url: M('Nasco+Halal+Food+Shinjuku'),
            image_url: IMG.kebab,
          },
        ],
      },
      {
        date: 'Nov 12',
        dow: 'Wed',
        title: 'Yanesen — old Tokyo',
        note: 'Yanaka, Nezu & Sendagi: low-rise shitamachi that survived the war. Nothing here overlaps Part 1.',
        activities: [
          {
            time: '9:30',
            title: 'Nezu Shrine torii tunnel',
            type: 'sight',
            area: 'Nezu',
            note: "One of Tokyo's oldest shrines, with its own vermilion torii tunnel — a fraction of Fushimi Inari's size and near-empty on a weekday morning.",
            map_url: M('Nezu+Shrine+Tokyo'),
            image_url: IMG.nezu,
          },
          {
            time: '11:30',
            title: 'Yanaka Ginza & Yanaka Cemetery',
            type: 'shop',
            area: 'Yanaka',
            note: 'A 170 m lantern-lined street of ~60 old shops — senbei, croquettes, cat-themed everything. The cemetery next door is a quiet maple-lined walk.',
            map_url: M('Yanaka+Ginza'),
            image_url: IMG.yanaka,
          },
          {
            time: '14:30',
            title: 'Rikugien garden',
            type: 'nature',
            area: 'Komagome',
            opt: true,
            note: 'Classic strolling garden, ~30 min walk from Nezu. Honest caveat: peak colour and the evening light-up usually land late Nov–early Dec, so the 12th may be early. Check before committing.',
            map_url: M('Rikugien+Garden'),
            image_url: IMG.rikugien,
          },
          {
            time: '19:00',
            title: 'Takuan Botantei, Shinjuku',
            type: 'food',
            area: 'Shinjuku',
            halal: true,
            note: 'Muslim-friendly Japanese — halal meat, alcohol-free seasonings, Muslim chef. Not formally certified, so confirm on the day. Halal options in Yanaka itself are thin.',
            map_url: M('Takuan+Botantei+Shinjuku'),
            image_url: IMG.jcuisine,
          },
        ],
      },
      {
        date: 'Nov 13',
        dow: 'Thu',
        title: 'Day trip — Nikkō or Hakone',
        note: 'Pick one; both are big autumn-leaf payoffs.',
        activities: [
          {
            time: 'Option A',
            title: 'Nikkō — shrines & waterfalls',
            type: 'nature',
            area: 'Tochigi',
            note: '~2h out. Tōshō-gū, Kegon Falls, Lake Chūzenji — prime koyo territory in mid-Nov.',
            map_url: M('Nikko+Toshogu'),
            image_url: IMG.nikko,
          },
          {
            time: 'Option B',
            title: 'Hakone loop',
            type: 'nature',
            area: 'Hakone',
            opt: true,
            note: 'Ropeway, Ōwakudani, lake pirate ship, Fuji views from the other side. Onsen town.',
            map_url: M('Hakone'),
            image_url: IMG.hakone,
          },
        ],
      },
      {
        date: 'Nov 14',
        dow: 'Fri',
        title: "Jumu'ah + Shimokitazawa",
        note: 'Camii and Shimokita are two stops apart on the Odakyu line — one clean westward run.',
        activities: [
          {
            time: '12:30',
            title: "Tokyo Camii — Jumu'ah, tour & halal market",
            type: 'culture',
            area: 'Yoyogi-Uehara',
            halal: true,
            note: "Turkey's grand mosque in Tokyo and the trip's one Camii visit: Friday prayer, the tiled interior (open to visitors outside prayer), and the halal grocery on the ground floor for take-home stock.",
            map_url: M('Tokyo+Camii'),
            image_url: IMG.camii,
          },
          {
            time: '15:00',
            title: 'Shimokitazawa — vintage & records',
            type: 'shop',
            area: 'Shimokitazawa',
            note: 'Two stops from Yoyogi-Uehara. Dense grid of second-hand clothing, record shops and tiny cafés — the opposite of the Ginza/Shibuya flagships you already did.',
            map_url: M('Shimokitazawa'),
            image_url: IMG.shimokita,
          },
        ],
      },
      {
        date: 'Nov 15',
        dow: 'Sat',
        title: 'Shinjuku home turf + farewell',
        note: 'Everything today is walkable or one stop from the flat — deliberately low-effort before flying.',
        activities: [
          {
            time: '9:30',
            title: 'Shinjuku Gyoen (autumn colour)',
            type: 'nature',
            area: 'Shinjuku',
            note: "One of Tokyo's best gardens and 15 min from the flat. Mid-to-late Nov is its window, so it should be better now than it was on the 12th.",
            map_url: M('Shinjuku+Gyoen'),
            image_url: IMG.gyoen,
          },
          {
            time: '13:00',
            title: 'Map Camera & Yodobashi, Nishi-Shinjuku',
            type: 'shop',
            area: 'Nishi-Shinjuku',
            note: 'The used film-camera hunt, without the trek to Nakano. Map Camera has floors of second-hand bodies and glass; Yodobashi sprawls across several buildings nearby.',
            map_url: M('Map+Camera+Shinjuku'),
            image_url: IMG.shinjuku,
          },
          {
            time: '16:00',
            title: 'Isetan depachika — souvenir sweep',
            type: 'shop',
            area: 'Shinjuku-sanchōme',
            note: 'Basement food hall: boxed sweets, tea, senbei — the easiest good souvenirs to carry home. Check ingredients on anything with filling. Then repack.',
            map_url: M('Isetan+Shinjuku'),
            image_url: IMG.jcuisine,
          },
          {
            time: '19:30',
            title: 'Farewell halal dinner',
            type: 'food',
            area: 'Shinjuku',
            halal: true,
            note: 'Send the trip off properly — Shinjuku Tei for the wagyu ramen if you want a repeat, or somewhere new around Shin-Ōkubo.',
            map_url: M('halal+restaurant+Shinjuku'),
            image_url: IMG.ramen,
          },
        ],
      },
      {
        date: 'Nov 16',
        dow: 'Sun',
        title: 'Departure',
        note: null,
        activities: [
          {
            time: '—',
            title: 'Airport transfer & fly out',
            type: 'transit',
            area: 'NRT / HND',
            note: "Narita: Skyliner/N'EX from Shinjuku. Haneda: direct trains. Leave buffer for a group of 5.",
            map_url: null,
            image_url: null,
          },
        ],
      },
    ],
  },

  /* ---------------- HOME ---------------- */
  /* Terminus, not a stop: this exists so the route ribbon draws the flight home
     out of Tokyo. It has no days and no section in the itinerary body. */
  {
    id: 'home',
    code: 'SYD',
    phase: 'Home',
    name: 'Sydney',
    jp: 'シドニー',
    date_start: 'Nov 17',
    date_end: 'Nov 17',
    nights: 0,
    travelers: 5,
    color: 'var(--home)',
    stay: 'Home',
    stay_note: '',
    climate: '',
    mosque: '',
    transit_icon: '✈',
    transit_html: '',
    is_terminus: true,
    days: [],
  },
];
